### ISSUE TITLE
About your model structure and your code in amber_cnn_sumstats

### ISSUE THREAD

**Issue by tlz4320** [vli31/CROTON#3]
Hello, and great work you have done.
These days, I want to transfer your network to pytorch and train my own model.
But after I load your CROTON.h5 file into tensorflow and plot_model by tensorflow utils, it shows the structure not as same as you give in amber_cnn_sumstats.py file.
And I also read Amber, is that in tensorflow_v1 backend only can save weight not model as I think?
So, which model should I use to reproduce your work, amber_cnn_sumstats or CROTON.h5.
In CROTON.h5, the conv1d layers will expand to 192 channel but Amber model seems 32?

**Comment by vli31** [comment]
The model architecture in CROTON.h5 should be used to reproduce our work. We searched for a reduced model for speed then expanded the channel numbers by a width scaling factor (i.e. 6).
