### ISSUE TITLE
Folder '30insertions' problem

### ISSUE THREAD

**Issue by Oh-Shmily** [vli31/CROTON#6]
In the file 'compile_sprout.py', i can't find the path 'data/Sprout/30insertions' and it also not mentioned in other code files:
```python
key_df_path = 'key_df.csv'
final_df_path = 'final_df.csv'

counts_dir = 'data/Sprout/counts'
insertions_dir = 'data/Sprout/30insertions'
master_dir = 'data/Sprout/master'
```
hope the author can fix this problem

**Comment by vli31** [comment]
hi! the "data" folder is not included in this repository because the files were too large –– the Sprout data is all processed from the Leenay 2019 paper, which can be accessed here: 
https://figshare.com/articles/dataset/Analyzed_T-Cell_DNA_Repair_Outcomes/6957125

**Comment by Oh-Shmily** [comment]
Thank you for your reply!
